name: Test typer
on:
  push:
    branches:
      - develop
jobs:
  test-typer:
    name: Test typer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Install cli
      run: make install
    - name: Get cli help
      run: container_runner --help
    - name: Clone repo
      run: git clone https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_PASSWORD }}@bitbucket.org/IslasGECI/hola.git
