name: Test typer
on:
  push:
    branches:
      - develop
jobs:
  test-typer:
    name: Test typer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Install cli
      run: make install && pip install pytest
    - name: Get container_runner CLI help
      run: container_runner --help
    - name: Clone repo
      run: git clone https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_PASSWORD }}@bitbucket.org/IslasGECI/hola.git
    - name: Test container_runner CLI
      run: pytest --verbose tests/test_cli.py
    - name: Remove mundo. Last set up step
      run: rm ./hola/mundo
